Language: en-US
Prefix: §3§l[dShop] §f
SalesTax: 25
UseShopCommand: true
DefaultShopName: Main
DisplayStockAsStack: false
DeliveryChargeScale: 1
NumberOfPlayer: 10
SaveLogs: true
CullLogs: true
LogCullAgeMinutes: 7200
LogCullTimeMinutes: 120
OnClickCloseButton_OpenStartPage: true
OpenStartPageInsteadOfDefaultShop: true
ShopInfoButtonIcon : OAK_SIGN