Language: en-US
Prefix: ยง3DShop3 ยง7| ยงf

Command.UseShopCommand: true
Command.OpenStartPageInsteadOfDefaultShop: true
Command.DefaultShopName: SampleShop
Command.PermissionCheckWhenCreatingAShopList: false

Shop.SalesTax: 25
Shop.DeliveryChargeScale: 0.3
Shop.DeliveryChargeMin: 1
Shop.DeliveryChargeMax: 25
Shop.NumberOfPlayer: 10
Shop.UseLegacyStockStabilization: false

UI.DisplayStockAsStack: false
UI.OpenStartPageWhenClickCloseButton: true
UI.Icons.CloseButton : BARRIER:0
UI.Icons.PageButton : PAPER:0
UI.Icons.ShopInfoButton : OAK_SIGN:0
UI.IntFormat: '###,###'
UI.DoubleFormat: '###,##0.00'
UI.LocalizedItemName: true
UI.UsePlaceholderAPI : true
UI.UseHexColorCode : true
UI.EnableInventoryClickSearch.StartPage: true
UI.EnableInventoryClickSearch.Shop: true

Log.SaveLogs: true
Log.LogFileNameFormat: MM_dd_yyyy
Log.CullLogs: true
Log.LogCullAgeMinutes: 7200
Log.LogCullTimeMinutes: 120
