name: DynamicShop
version: ${project.version}
main: me.sat7.dynamicshop.DynamicShop
depend: [Vault]
softdepend: [PlaceholderAPI, Jobs, LocaleLib]
api-version: 1.18
authors: [sat7, LincolnJota]
description: Full GUI shop with dynamic prices
commands:
  DynamicShop:
    description: "Full GUI shop with dynamic prices"
    aliases: [ds]
  shop:
    description: "Open shop menu"
permissions:
  dshop.use:
    description: Allows use of the /ds command
    default: true
  dshop.use.qsell:
    description: Allows use of the /ds qsell command
    default: true